FROM debian:bullseye
RUN \
    apt-get update && \
    apt-get install -y \
    inkscape \
    ruby \
    fonts-noto \
    locales
COPY . .
RUN \
    locale -a && \
    locale-gen sv_SE.UTF-8
RUN \
    gem build inkmake.gemspec && \
    gem install inkmake
ENTRYPOINT ["inkmake"]
